### PR TITLE
Use node-fetch in own statement

### PR DESCRIPTION
**Pull request by olivereisenhut**
This is proposed as hot-fix for #10. I put the the `require('note-fetch')` on in its own line so it's not executed in browser environment and the webpack compiler doesn't try to resolve a file. This is a non-breaking change so existing users aren't affected.

### CODE REVIEW

**Comment by ajonno** [comment]
Great stuff, any idea when this will be merged?

**Comment by nirinchev** [comment]
Sorry for the delay, I'll try to review this by the end of the week or early next week and get it merged.

**Comment by ajonno** [comment]
hi @nirinchev, any update on this ?

**Comment by Drivez** [comment]
hello @nirinchev, any new update on this?

**Comment by olivereisenhut** [comment]
Sorry thats my bad. No there is no reason to delete the lock file. Will fix it asap.

**Comment by olivereisenhut** [comment]
I reviewed the commits and its not actually deleting the `package-lock.json` it was just updated because `node-fetch` was added as dependency.

**Comment by kraenhansen** [comment]
Okay - I can see the file is actually not deleted, but I am surprised to see that it has 1237 lines deleted but only 127 lines added when the only change to the package.json is adding `fetch-node` and pinning TypeScript to an earlier version. Do you know why that happened?

**Comment by olivereisenhut** [comment]
I regenerated the `package-lock.json` it should now be up-to-date.

**Comment by nirinchev** [comment]
Thanks!

**Comment by Drivez** [comment]
do you need to bump the package.json version for the npm package to update?

**Comment by ajonno** [comment]
Thanks for the update. Has the version been updated so we can pull it down from npm and try it?

**Comment by nirinchev** [comment]
Yep - I pushed an update yesterday, feel free to pull it and let us know if there's anything broken :)

**Pull request merged**
